import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import NextAuthSEssionProvider from "@/providers/NextAuthSEssionProvider";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['400', '600', '700'],
  subsets: ["latin"],

})

export const metadata = {
  title: "SnackPanda-A snacks Delivery App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <NextAuthSEssionProvider>

        <body
          className={`${poppins.className} ${geistMono.variable} antialiased`}
        >
          <Navbar />
          <main className="">
            {children}
          </main>
          <Footer></Footer>
        </body>
      </NextAuthSEssionProvider>
    </html>
  );
}
